// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxwamuzhcggvtoweyjnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4d2FtdXpoY2dndnRvd2V5am53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjYzNjQsImV4cCI6MjA3MzEwMjM2NH0.yXRnEDUzGLuWPlf_kfk9eHEgnFWPalOrLe5qMUGMzCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});